dataset:
  name: aptos
  root: data/aptos
  split: [0.8, 0.2]
  num_keypoints: 50
  sift_sigma: 1.6
  distance_sigma_px: 10
model:
  gnn_hidden_dim: 32
  num_layers: 4
  sortpool_k: 50
  conv_hidden_dims: [16, 32]
batch_size: 64
max_epochs: 210
seed: 42
